server:
  port: 8889
  servlet:
    context-path: /springbootdemos
#Redis集群配置
spring:
  redis:
#    cluster:
#      nodes: 10.168.12.51:5100,10.168.12.51:5101,10.168.12.63:6300,10.168.12.63:6301,10.168.12.64:7300,10.168.12.64:7301
    host: 127.0.0.1
    port: 6379
    timeout: 10000
    database: 0
    lettuce:
      pool:
        max-active: 100                         #连接池最大连接数
        max-idle: 10                            #连接池中的最大空闲连接
        max-wait: -1                            #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0
        timeout: 0                                #连接超时时间（毫秒）
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #监控统计拦截的filters
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/noodles?characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
      username: root
      #password: admin123
      password: Fujitsu913
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  mybatis:
    type-aliases-package: com.noodles.springbootdemos.bean
    mapper-locations: classpath:com/noodles/springbootdemos/mapper/*Mapper.xml
    config-location: classpath:com/noodles/springbootdemos/mapper/mybatis.cfg.xml
  #分页插件
  pagehelper:
    helper-dialect: mysql
    params: count=countsql
    reasonable: false
    support-methods-arguments: true