# Redis集群配置
spring:
  redis:
    cluster:
      nodes: 10.180.14.51:5100,10.180.14.51:5101,10.180.14.52:5200,10.180.14.52:5201,10.180.14.53:5300,10.180.14.53:5301
    timeout: 1000
    database: 0
    lettuce:
      pool:
        max-active: 100                         #连接池最大连接数
        max-idle: 10                            #连接池中的最大空闲连接
        max-wait: -1                            #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0
        timeout: 0                                #连接超时时间（毫秒）

